// SPDX-FileCopyrightText: 2009-2020 TRUMPF Laser GmbH, authors: C-Labs
//
// SPDX-License-Identifier: MPL-2.0

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMyVThings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDMyVThings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new V-Thing.
        /// </summary>
        internal static string AddnewVThing528661 {
            get {
                return ResourceManager.GetString("AddnewVThing528661", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property.
        /// </summary>
        internal static string AddProperty939805 {
            get {
                return ResourceManager.GetString("AddProperty939805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Properties.
        /// </summary>
        internal static string AllProperties100123 {
            get {
                return ResourceManager.GetString("AllProperties100123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Properties.
        /// </summary>
        internal static string AllProperties152462 {
            get {
                return ResourceManager.GetString("AllProperties152462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Properties....
        /// </summary>
        internal static string AllProperties27010 {
            get {
                return ResourceManager.GetString("AllProperties27010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Properties.
        /// </summary>
        internal static string AllProperties957277 {
            get {
                return ResourceManager.GetString("AllProperties957277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Properties.
        /// </summary>
        internal static string AmountProperties598472 {
            get {
                return ResourceManager.GetString("AmountProperties598472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        internal static string AutoStart96821 {
            get {
                return ResourceManager.GetString("AutoStart96821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Settings....
        /// </summary>
        internal static string BaseSettings385815 {
            get {
                return ResourceManager.GetString("BaseSettings385815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Labs.
        /// </summary>
        internal static string CLabs333476 {
            get {
                return ResourceManager.GetString("CLabs333476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on Restart.
        /// </summary>
        internal static string ContinueonRestart992144 {
            get {
                return ResourceManager.GetString("ContinueonRestart992144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Type.
        /// </summary>
        internal static string ControlType347647 {
            get {
                return ResourceManager.GetString("ControlType347647", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown.
        /// </summary>
        internal static string Countdown438154 {
            get {
                return ResourceManager.GetString("Countdown438154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown.
        /// </summary>
        internal static string Countdown601774 {
            get {
                return ResourceManager.GetString("Countdown601774", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        internal static string CurrentValue636641 {
            get {
                return ResourceManager.GetString("CurrentValue636641", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-Generator.
        /// </summary>
        internal static string DataGenerator350949 {
            get {
                return ResourceManager.GetString("DataGenerator350949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-Verifier.
        /// </summary>
        internal static string DataVerifier936503 {
            get {
                return ResourceManager.GetString("DataVerifier936503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable723846 {
            get {
                return ResourceManager.GetString("Disable723846", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags190631 {
            get {
                return ResourceManager.GetString("Flags190631", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags706452 {
            get {
                return ResourceManager.GetString("Flags706452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (ms).
        /// </summary>
        internal static string Frequencyms741318 {
            get {
                return ResourceManager.GetString("Frequencyms741318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.c-labs.com.
        /// </summary>
        internal static string httpwwwclabscom333476 {
            get {
                return ResourceManager.GetString("httpwwwclabscom333476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string IsActive82651 {
            get {
                return ResourceManager.GetString("IsActive82651", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading601774 {
            get {
                return ResourceManager.GetString("Loading601774", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Time.
        /// </summary>
        internal static string LoopTime96821 {
            get {
                return ResourceManager.GetString("LoopTime96821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Global.
        /// </summary>
        internal static string MakeGlobal758791 {
            get {
                return ResourceManager.GetString("MakeGlobal758791", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxim Latency (ms).
        /// </summary>
        internal static string MaximLatencyms44483 {
            get {
                return ResourceManager.GetString("MaximLatencyms44483", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        internal static string MaxValue563606 {
            get {
                return ResourceManager.GetString("MaxValue563606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory-Tags.
        /// </summary>
        internal static string MemoryTags239667 {
            get {
                return ResourceManager.GetString("MemoryTags239667", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Latency (ms).
        /// </summary>
        internal static string MinimumLatencyms44483 {
            get {
                return ResourceManager.GetString("MinimumLatencyms44483", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        internal static string MinValue204801 {
            get {
                return ResourceManager.GetString("MinValue204801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms to Trigger.
        /// </summary>
        internal static string MstoTrigger260442 {
            get {
                return ResourceManager.GetString("MstoTrigger260442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name82651 {
            get {
                return ResourceManager.GetString("Name82651", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Property Name.
        /// </summary>
        internal static string NewPropertyName27010 {
            get {
                return ResourceManager.GetString("NewPropertyName27010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMI Control Type.
        /// </summary>
        internal static string NMIControlType831825 {
            get {
                return ResourceManager.GetString("NMIControlType831825", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMI Elements.
        /// </summary>
        internal static string NMIElements957277 {
            get {
                return ResourceManager.GetString("NMIElements957277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMI Screen.
        /// </summary>
        internal static string NMIScreen347647 {
            get {
                return ResourceManager.GetString("NMIScreen347647", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMI Screen.
        /// </summary>
        internal static string NMIScreen744620 {
            get {
                return ResourceManager.GetString("NMIScreen744620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMI Settings....
        /// </summary>
        internal static string NMISettings581000 {
            get {
                return ResourceManager.GetString("NMISettings581000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Properties.
        /// </summary>
        internal static string NumberProperties187329 {
            get {
                return ResourceManager.GetString("NumberProperties187329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Properties.
        /// </summary>
        internal static string NumberProperties295308 {
            get {
                return ResourceManager.GetString("NumberProperties295308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties187329 {
            get {
                return ResourceManager.GetString("Properties187329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties239667 {
            get {
                return ResourceManager.GetString("Properties239667", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties295308 {
            get {
                return ResourceManager.GetString("Properties295308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties per Second.
        /// </summary>
        internal static string PropertiesperSecond546134 {
            get {
                return ResourceManager.GetString("PropertiesperSecond546134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties per Second.
        /// </summary>
        internal static string PropertiesperSecond849298 {
            get {
                return ResourceManager.GetString("PropertiesperSecond849298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property count.
        /// </summary>
        internal static string Propertycount904939 {
            get {
                return ResourceManager.GetString("Propertycount904939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property counter.
        /// </summary>
        internal static string Propertycounter208103 {
            get {
                return ResourceManager.GetString("Propertycounter208103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Picker.
        /// </summary>
        internal static string PropertyPicker758791 {
            get {
                return ResourceManager.GetString("PropertyPicker758791", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload403288 {
            get {
                return ResourceManager.GetString("Reload403288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload542832 {
            get {
                return ResourceManager.GetString("Reload542832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload598472 {
            get {
                return ResourceManager.GetString("Reload598472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Counter.
        /// </summary>
        internal static string ResetCounter741318 {
            get {
                return ResourceManager.GetString("ResetCounter741318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Name.
        /// </summary>
        internal static string SensorName9616 {
            get {
                return ResourceManager.GetString("SensorName9616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Type.
        /// </summary>
        internal static string SensorType9616 {
            get {
                return ResourceManager.GetString("SensorType9616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Units.
        /// </summary>
        internal static string SensorUnits845996 {
            get {
                return ResourceManager.GetString("SensorUnits845996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Value Name.
        /// </summary>
        internal static string SensorValueName204801 {
            get {
                return ResourceManager.GetString("SensorValueName204801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the VThing-Type of this tag.
        /// </summary>
        internal static string SettheVThingTypeofthistag995446 {
            get {
                return ResourceManager.GetString("SettheVThingTypeofthistag995446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Settings793657 {
            get {
                return ResourceManager.GetString("Settings793657", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Settings796959 {
            get {
                return ResourceManager.GetString("Settings796959", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string Settings901637 {
            get {
                return ResourceManager.GetString("Settings901637", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source....
        /// </summary>
        internal static string Source152462 {
            get {
                return ResourceManager.GetString("Source152462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Property.
        /// </summary>
        internal static string SourceProperty511267 {
            get {
                return ResourceManager.GetString("SourceProperty511267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Thing.
        /// </summary>
        internal static string SourceThing511267 {
            get {
                return ResourceManager.GetString("SourceThing511267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over when zero.
        /// </summary>
        internal static string StartOverwhenzero992144 {
            get {
                return ResourceManager.GetString("StartOverwhenzero992144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value.
        /// </summary>
        internal static string StartValue633339 {
            get {
                return ResourceManager.GetString("StartValue633339", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Timer.
        /// </summary>
        internal static string StopTimer814431 {
            get {
                return ResourceManager.GetString("StopTimer814431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing for Property Subs.
        /// </summary>
        internal static string ThingforPropertySubs849298 {
            get {
                return ResourceManager.GetString("ThingforPropertySubs849298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing Picker.
        /// </summary>
        internal static string ThingPicker399986 {
            get {
                return ResourceManager.GetString("ThingPicker399986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plug-in hosts many different functions and other virtual devices.
        /// </summary>
        internal static string Thispluginhostsmanydifferentfunctionsandothervirtualdevices333476 {
            get {
                return ResourceManager.GetString("Thispluginhostsmanydifferentfunctionsandothervirtualdevices333476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick time in ms.
        /// </summary>
        internal static string Ticktimeinms633339 {
            get {
                return ResourceManager.GetString("Ticktimeinms633339", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Timer542832 {
            get {
                return ResourceManager.GetString("Timer542832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger796959 {
            get {
                return ResourceManager.GetString("Trigger796959", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Cnt.
        /// </summary>
        internal static string TriggerCnt901637 {
            get {
                return ResourceManager.GetString("TriggerCnt901637", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Now.
        /// </summary>
        internal static string TriggerNow455626 {
            get {
                return ResourceManager.GetString("TriggerNow455626", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Things.
        /// </summary>
        internal static string VirtualThings692281 {
            get {
                return ResourceManager.GetString("VirtualThings692281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Things.
        /// </summary>
        internal static string VirtualThings974671 {
            get {
                return ResourceManager.GetString("VirtualThings974671", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Sensor Settings....
        /// </summary>
        internal static string VSensorSettings650811 {
            get {
                return ResourceManager.GetString("VSensorSettings650811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-State Sensor.
        /// </summary>
        internal static string VStateSensor650811 {
            get {
                return ResourceManager.GetString("VStateSensor650811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Things List.
        /// </summary>
        internal static string VThingsList887466 {
            get {
                return ResourceManager.GetString("VThingsList887466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Thing Type.
        /// </summary>
        internal static string VThingType995446 {
            get {
                return ResourceManager.GetString("VThingType995446", resourceCulture);
            }
        }
    }
}
